-- Table: admin.gmail_servers

-- DROP TABLE IF EXISTS admin.gmail_servers;

CREATE TABLE IF NOT EXISTS admin.gmail_servers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    server_name character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    provider_name character varying(20) COLLATE pg_catalog."default",
    client_secret character varying(100) COLLATE pg_catalog."default" NOT NULL,
    client_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    created_date date NOT NULL,
    last_updated_date date NOT NULL,
    provider_id bigint NOT NULL,
    CONSTRAINT seq_id_gmail_servers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS admin.gmail_servers
    OWNER to admin;